apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"frontend:v1"},"fieldPath":"spec.template.spec.containers[?(@.name==\"frontend\")].image"}]'
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/engarjur/frontend@sha256:96de6592c21934262c02b75d41b9a33e3cf3eb26e6497e4030831ab73699fc86
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
